### ISSUE TITLE
Focus-ring is not applied when the element receives focus in vaadin-grid interaction mode

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-control-state-mixin#33] opened 2018-01-27 22:27 UTC
If the user enters the interaction mode of vaadin-grid by pressing <kbd>Enter</kbd> on a cell that contains a Vaadin control as the first focusable child element, the control does not receive the `focus-ring` state even though it is focused.

The root cause is that we only check if the <kbd>Tab</kbd> was pressed when the control receives focus: https://github.com/vaadin/vaadin-control-state-mixin/blob/master/vaadin-control-state-mixin.html#L145

**Comment by platosha** [comment] 2018-02-12 12:01
This is tricky, because `<vaadin-grid>`’s interaction mode focus is, actually, programmatic, so not directly from keyboard.

I’ve noticed that in `Polymer.IronButtonState` behavior they rely on pointer down instead a particular keyboard key: https://github.com/PolymerElements/iron-behaviors/blob/c631e7c6c8fc79f43aa1c9ba1c65743ac9848bff/iron-button-state.html#L127 Should we, perhaps, do the same?

**Comment by web-padawan** [comment] 2020-02-20 09:56
> interaction mode focus is, actually, programmatic

Which is actually a duplicate of #50 

> rely on pointer down instead a particular keyboard key

Implemented this in [focus-visible-mixin](https://github.com/vaadin/component-mixins/blob/a7487fbfc7036e78039040eb11ec65b4df62816d/packages/focus-visible-mixin/focus-visible-mixin.ts#L79-L81) for the next generation components.

We might want to backport that fix, but let's discuss that in #50.

**Closed as completed by web-padawan** 2020-02-20 09:56 UTC
